# Generated by Django 4.1.3 on 2022-11-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_type_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='Dry White', max_length=25),
        ),
    ]
